# Secrets + stacks
# only part from 3.1 version

version : "3.1"
services:
  psql:
    image: postgres:latest

    secrets: 
      - psql_user
      - psql_pass

    environment:
      POSTGRES_USERNAME_FILE: /run/secrets/psql_user   
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass


secrets:
  psql_user:
    file: ./user.txt

  psql_pass:
    file: ./pass.txt  



    